### ISSUE TITLE
[Bug] error occured when gpinitsystem on redhat8.9 or openEuler 22.03 (LTS-SP4) or Anolis OS 8.6,after rpm/Compile install successfully.

### ISSUE THREAD

**Issue by fsmiledream** [cloudberrydb/cloudberrydb#618] opened 2024-09-06 09:09 UTC
### Cloudberry Database version

cloudberrydb-1.5.4

### What happened

After rpm/Compile install successfully,  when gpinitsystem, error 'Error: unable to import module: No module named 'pg''happened,then after 'pip3 install pg -i https://pypi.tuna.tsinghua.edu.cn/simple/', another error 'File "/usr/local/lib/python3.9/site-packages/pg/__init__.py", line 3
    async SyntaxError: invalid syntax' happened when used python3.9,error'AttributeError: 'NoneType' object has no attribute 'glGetError''happend when used python3.6,but now actually, database is open ,but cannot stop or start ;  please see below pictures  like my describe .
![makeinstall successful](https://github.com/user-attachments/assets/13ae280f-2b98-4047-8ffa-6782ed76585e)
![openruler22 03 initsystem error1](https://github.com/user-attachments/assets/09fdd018-4058-4eb1-9a91-d398c4689dd8)
![openruler22 03 initsystem error2](https://github.com/user-attachments/assets/a5ec0d08-94f2-4688-adaa-9f32ea943bad)
![redhat8 9+python3 6 initsystem error](https://github.com/user-attachments/assets/6a95fb90-988c-4676-9fb2-3b31766a79dc)
![redhat8 9+python3 9 initsystem error](https://github.com/user-attachments/assets/6aec0375-a09e-4bcc-8743-d1d432c85113)
![cbdb opened but  error when stop](https://github.com/user-attachments/assets/0ea9aa9d-52d3-4e54-b4fd-139d46f49fdf)
![Anolis8 6 initsystem error](https://github.com/user-attachments/assets/99421c50-9dbd-4e22-8c30-3b95381cbe0a)

### How to reproduce

I suggest reduce dependencies.   avoid ''No module named 'pg'error.

### Operating System

 redhat8.9 or openEuler 22.03 (LTS-SP4) or Anolis OS 8.6

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment] 2024-09-06 09:16
Hi @fsmiledream the 1.5.4.rpm is a little outdated. Please try the latest 1.6.0 version to see if it works. Our 1.6.0 version has a robust RPM package and has been tested many times and solved the dependencies problem.

If 1.6.0 has the same issue, we can continue to look into the cause.

cc @Zhangbaowen-Hashdata @edespino

**Comment by gongxun0928** [comment] 2024-10-08 07:56
Duplicate of #620

**Closed** 2024-10-09 01:42 UTC
Labels: type: Bug
