### ISSUE TITLE
change type of logerrors in pg_exttable from char to boolean

### ISSUE THREAD

**Issue by my-ship-it** [cloudberrydb/cloudberrydb#74] opened 2023-07-24 08:14 UTC
```
postgres=# select version();
----------------------------------------------------------------------------------------
 PostgreSQL 14.4 (Cloudberry Database 1.3.0 build commit:bb9d07938bab13f6117bd565d5c71ca878bc4dbe) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11), 64-bit compiled on May 24 2023 16:39:21
(1 row)


postgres=# \d pg_exttable;
               View "pg_catalog.pg_exttable"
     Column      |  Type   | Collation | Nullable | Default 
-----------------+---------+-----------+----------+---------
 reloid          | oid     |           |          | 
 urilocation     | text[]  |           |          | 
 execlocation    | text[]  |           |          | 
 fmttype         | "char"  |           |          | 
 fmtopts         | text    |           |          | 
 options         | text[]  |           |          | 
 command         | text    |           |          | 
 rejectlimit     | integer |           |          | 
 rejectlimittype | "char"  |           |          | 
 logerrors       | "char"  |           |          | 
 encoding        | integer |           |          | 
 writable        | boolean |           |          | 


db1=# select version();

---------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.4 build commit:f3782c6dd89c9b6565a84518174ed4dd448f3293 Open Source) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on 
Jun 15 2023 01:11:10 Bhuvnesh C.
(1 row)


db_gp7=# \d pg_exttable
               View "pg_catalog.pg_exttable"
     Column      |  Type   | Collation | Nullable | Default 
-----------------+---------+-----------+----------+---------
 reloid          | oid     |           |          | 
 urilocation     | text[]  |           |          | 
 execlocation    | text[]  |           |          | 
 fmttype         | "char"  |           |          | 
 fmtopts         | text    |           |          | 
 options         | text[]  |           |          | 
 command         | text    |           |          | 
 rejectlimit     | integer |           |          | 
 rejectlimittype | "char"  |           |          | 
 logerrors       | boolean |           |          | 
 encoding        | integer |           |          | 
 writable        | boolean |           |          |
```

Need to cherry pick: https://github.com/greenplum-db/gpdb/pull/14123

**Comment by Ray-Eldath** [comment] 2023-08-03 09:49
Close as duplicate of #21.

**Closed by Ray-Eldath** 2023-08-03 09:49 UTC
