### ISSUE TITLE
[Bug] [OS Specific][oe2309] unexpected execution of aborted due to PL/Perl compilation errors

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#509] opened 2024-07-09 07:59 UTC
### Cloudberry Database version

 PostgreSQL 14.4 (Cloudberry Database 1.5.5+dev.77.g5024c64f build 79256 commit:5024c64f) 

### What happened

test mapred                       ... FAILED     1443 ms

```
@@ -507,26 +501,28 @@
 mapreduce
 ---------------------
 STDERR> ERROR:  syntax error at line 18, near "[]"
-STDERR> syntax error at line 20, near ";
-STDERR>  }"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_1977_grep_map"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482750_grep_map"
 STDERR> Error: Object creation Failure
 STDERR> ERROR:  syntax error at line 28, near "[]"
-STDERR> syntax error at line 29, near ";
-STDERR>  }"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_1992_grep_map"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482758_grep_map"
 STDERR> Error: Object creation Failure
 STDERR> ERROR:  syntax error at line 37, near "[]"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2000_grep_map"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482766_grep_map"
 STDERR> Error: Object creation Failure
 STDERR> ERROR:  syntax error at line 45, near "[]"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2011_grep_map"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482774_grep_map"
 STDERR> Error: Object creation Failure
 STDERR> ERROR:  syntax error at line 53, near "[]"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2020_grep_map"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482782_grep_map"
 STDERR> Error: Object creation Failure
 STDERR> ERROR:  syntax error at line 67, near "}GABLECK"
-STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_52431_mymap"
+STDERR> Execution of aborted due to compilation errors.
+STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482790_mymap"
 STDERR> Error: Object creation Failure
 STDERR> WARNING: unset parameter - myMap(key => NULL)
 STDERR> mapreduce_PID_run_1
~                             
```

Actual results
```
--
-- Test 7) Syntax error lineno reporting
--
SELECT mapreduce('/code/cbdb_src/gpcontrib/gpmapreduce/yml/perlerror.yml') ORDER BY 1;
mapreduce
---------------------
STDERR> ERROR:  syntax error at line 18, near "[]"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482750_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 28, near "[]"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482758_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 37, near "[]"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482766_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 45, near "[]"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482774_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 53, near "[]"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482782_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 67, near "}GABLECK"
STDERR> Execution of aborted due to compilation errors.
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_482790_mymap"
STDERR> Error: Object creation Failure
STDERR> WARNING: unset parameter - myMap(key => NULL)
STDERR> mapreduce_482798_run_1
STDERR> ERROR:  }GABLECK!{ at line 85.
STDERR> CONTEXT:  PL/Perl function "mapreduce_482798_mymap"
STDERR> Error: Execution Failure
STDERR>
STDOUT>


```

### What you think should happen instead

expected outputs 
```
--
-- Test 7) Syntax error lineno reporting
--
SELECT mapreduce('/code/cbdb_src/gpcontrib/gpmapreduce/yml/perlerror.yml') ORDER BY 1;
mapreduce
---------------------
STDERR> ERROR:  syntax error at line 18, near "[]"
STDERR> syntax error at line 20, near ";
STDERR>  }"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_1977_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 28, near "[]"
STDERR> syntax error at line 29, near ";
STDERR>  }"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_1992_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 37, near "[]"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2000_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 45, near "[]"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2011_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 53, near "[]"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_2020_grep_map"
STDERR> Error: Object creation Failure
STDERR> ERROR:  syntax error at line 67, near "}GABLECK"
STDERR> CONTEXT:  compilation of PL/Perl function "mapreduce_52431_mymap"
STDERR> Error: Object creation Failure
STDERR> WARNING: unset parameter - myMap(key => NULL)
STDERR> mapreduce_PID_run_1
STDERR> ERROR:  }GABLECK!{ at line 85.
STDERR> CONTEXT:  PL/Perl function "mapreduce_52435_mymap"
STDERR> Error: Execution Failure
STDERR>
STDOUT>
```

### How to reproduce

cd /code/cbdb_src/gpcontrib/gpmapreduce
make installcheck

### Operating System

oe2309:x86_64

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by gfphoenix78** [comment] 2024-10-09 11:06
gpmapreduce was disabled in current cloudberrydb. The issue is caused by a higher version of perl. If you prefer to use this extension, please consider this PR https://github.com/cloudberrydb/cloudberrydb/pull/658

**Comment by gfphoenix78** [comment] 2024-10-09 11:07
I'll close this issue, since gpmapreduce was disabled.

**Closed by gfphoenix78** 2024-10-09 11:07 UTC
Labels: type: Bug, priority: High
